title = "PTR 2024"
theme = "hugo-geekdoc"
staticDir = ["static"]
defaultContentLanguage = "en"

pluralizeListTitles = false

pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

enableRobotsTXT = false

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  geekdocLogo = "geek2022beli.svg"
  geekdocNextPrev = true
  geekdocBreadcrumb = false
  geekdocSearch = false

#pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = true
#pygmentsUseClasses = true
#
#[module]
#    [module.hugoVersion]
#        extended = true
#        min = "0.55.0"
#
#[[menu.main]]
#    name = "Uvod"
#    url = "/"
#    weight = 1
#
#[[menu.main]]
#    name = "Naloge"
#    url = "/exercises/"
#    weight = 2
#
#[params]
#    BookTheme = "light"
#    BookToC = false
#    BookMenuBundle = "/menu"
#    BookSearch = false
#    BookComments = false
#
#[[menu.after]]
#  name = "GitHub"
#  url = "https://github.com/ptr-geeks"
#  weight = 10
